src/java/semgrado/controlador/MunicipioController.java
package semgrado.controlador;

import semgrado.entidades.Municipio;
import semgrado.controlador.util.JsfUtil;
import semgrado.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("municipioController")
@SessionScoped
public class MunicipioController implements Serializable {

    @EJB
    private semgrado.controlador.MunicipioFacade ejbFacade;
    private List<Municipio> items = null;
    private Municipio selected;

    public MunicipioController() {
    }

    public Municipio getSelected() {
        return selected;
    }

    public void setSelected(Municipio selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private MunicipioFacade getFacade() {
        return ejbFacade;
    }

    public Municipio prepareCreate() {
        selected = new Municipio();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("MunicipioCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("MunicipioUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("MunicipioDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Municipio> getItems() {
        
        items = getFacade().findAll();
        
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if(persistAction == PersistAction.CREATE){
                    getFacade().create(selected);
                }else if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Municipio getMunicipio(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Municipio> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Municipio> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Municipio.class)
    public static class MunicipioControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            MunicipioController controller = (MunicipioController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "municipioController");
            return controller.getMunicipio(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Municipio) {
                Municipio o = (Municipio) object;
                return getStringKey(o.getCodigo());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Municipio.class.getName()});
                return null;
            }
        }

    }

}

web/municipio/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="MunicipioCreateDlg" widgetVar="MunicipioCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateMunicipioTitle}">
            <h:form id="MunicipioCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{municipioController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateMunicipioLabel_codigo}" for="codigo" />
                        <p:inputText id="codigo" value="#{municipioController.selected.codigo}" title="#{bundle.CreateMunicipioTitle_codigo}" required="true" requiredMessage="#{bundle.CreateMunicipioRequiredMessage_codigo}"/>
                        <p:outputLabel value="#{bundle.CreateMunicipioLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{municipioController.selected.nombre}" title="#{bundle.CreateMunicipioTitle_nombre}" />
                        <p:outputLabel value="#{bundle.CreateMunicipioLabel_fkDepartamento}" for="fkDepartamento" />
                        <p:selectOneMenu id="fkDepartamento" value="#{municipioController.selected.fkDepartamento}" required="true" requiredMessage="#{bundle.EditMunicipioRequiredMessage_fkDepartamento}">
                            <f:selectItems value="#{departamentoController.itemsAvailableSelectOne}"
                                           var="fkDepartamentoItem"
                                           itemValue="#{fkDepartamentoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{municipioController.create}" value="#{bundle.Save}" update="display,:MunicipioListForm:datalist,:growl" oncomplete="handleSubmit(args,'MunicipioCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" immediate="true" onclick="MunicipioCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/municipio/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="MunicipioEditDlg" widgetVar="MunicipioEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditMunicipioTitle}">
            <h:form id="MunicipioEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{municipioController.selected != null}">
                        <p:outputLabel value="#{bundle.EditMunicipioLabel_codigo}" for="codigo" />
                        <p:inputText id="codigo" value="#{municipioController.selected.codigo}" title="#{bundle.EditMunicipioTitle_codigo}" required="true" requiredMessage="#{bundle.EditMunicipioRequiredMessage_codigo}"/>
                        <p:outputLabel value="#{bundle.EditMunicipioLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{municipioController.selected.nombre}" title="#{bundle.EditMunicipioTitle_nombre}" />
                        <p:outputLabel value="#{bundle.EditMunicipioLabel_fkDepartamento}" for="fkDepartamento" />
                        <p:selectOneMenu id="fkDepartamento" value="#{municipioController.selected.fkDepartamento}" required="true" requiredMessage="#{bundle.EditMunicipioRequiredMessage_fkDepartamento}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{departamentoController.itemsAvailableSelectOne}"
                                           var="fkDepartamentoItem"
                                           itemValue="#{fkDepartamentoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{municipioController.update}" value="#{bundle.Save}" update="display,:MunicipioListForm:datalist,:growl" oncomplete="handleSubmit(args, 'MunicipioEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="MunicipioEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/municipio/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListMunicipioTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="MunicipioListForm">
                <p:panel header="#{bundle.ListMunicipioTitle}">
                    <p:dataTable id="datalist" value="#{municipioController.items}" var="item"
                                 selectionMode="single" selection="#{municipioController.selected}"
                                 paginator="true"
                                 rowKey="#{item.codigo}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMunicipioTitle_codigo}"/>
                            </f:facet>
                            <h:outputText value="#{item.codigo}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMunicipioTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListMunicipioTitle_fkDepartamento}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkDepartamento}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{municipioController.prepareCreate}" update=":MunicipioCreateForm" oncomplete="PF('MunicipioCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":MunicipioViewForm" oncomplete="PF('MunicipioViewDialog').show()" disabled="#{empty municipioController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":MunicipioEditForm" oncomplete="PF('MunicipioEditDialog').show()" disabled="#{empty municipioController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{municipioController.destroy}" update=":growl,datalist" disabled="#{empty municipioController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/municipio/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="MunicipioViewDlg" widgetVar="MunicipioViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewMunicipioTitle}">
            <h:form id="MunicipioViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{municipioController.selected != null}">
                        <h:outputText value="#{bundle.ViewMunicipioLabel_codigo}"/>
                        <h:outputText value="#{municipioController.selected.codigo}" title="#{bundle.ViewMunicipioTitle_codigo}"/>
                        <h:outputText value="#{bundle.ViewMunicipioLabel_nombre}"/>
                        <h:outputText value="#{municipioController.selected.nombre}" title="#{bundle.ViewMunicipioTitle_nombre}"/>
                        <h:outputText value="#{bundle.ViewMunicipioLabel_fkDepartamento}"/>
                        <h:outputText value="#{municipioController.selected.fkDepartamento}" title="#{bundle.ViewMunicipioTitle_fkDepartamento}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="MunicipioViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>